# List of coherence servers
servers:
  - host: "localhost"
    port: 7199
    #serviceUrl: 
    username: ""
    password: ""
    #Metric Overrides. Change this if you want to transform the metric key or value or its properties.
    metricOverrides:
      - metricKey: ".*"
        disabled: true

      - metricKey: ".*Platform.*"
        disabled: false


# number of concurrent tasks
numberOfThreads: 10

#timeout for the thread in seconds
threadTimeout: 30

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Coherence|"

#Metric Overrides for all servers. Change this if you want to transform the metric key or value or its properties.
#metricOverrides:
#  - metricKey: ".*Ratio.*"
#    postfix: "Percent"
#    multiplier: 100
#    disabled: false
#    timeRollup: "AVERAGE"
#    clusterRollup: "COLLECTIVE"
#    aggregator: "SUM"
#
#
#  - metricKey: ".*Cache.*Rate.*"
#    postfix: "Percent"
#    multiplier: 100